### ISSUE TITLE
Floating Point Accuracy in Booster Multiplier

### ISSUE THREAD

**Issue by drac-dot-gay** [SorenNeedsCoffee/garbage-can-csharp#14]
While writing unit tests for Boosters in the [features/boosters](/murl-digital/garbage-can/tree/feature/boosters) branch, I came across an issue where multipliers tended to be inaccurate

![image](https://user-images.githubusercontent.com/8054329/128404219-8e9e1e0a-6fbd-4c19-9349-5d0fe3b93f71.png)

Fixes could include clamping the decimal places (as seen in the XP user model), changing the multiplier datatype, or perhaps a combination of these or other things. It could also be negligible, this will need to be discussed most likely.

**Comment by TGrannen** [comment]
The root cause of this bug is how floats store their data internally and how they are added together. Essentially the problem is the `floatA + floatB + floatC == floatA + (floatB + floatC)` isn't always true. However, using the `Decimal` datatype instead of floats alleviates this problem. See this dotnet fiddle link: https://dotnetfiddle.net/jGMtM8

I've fixed the broken tests with a small change to the expected value, but it might be better to switch over to decimals at some point to not have to worry about this problem in the future.
